"""empty message

Revision ID: 508eb8ac54f8
Revises: 6b20f94b155f
Create Date: 2023-09-25 10:36:30.261401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508eb8ac54f8'
down_revision = '6b20f94b155f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
